---

- name: create new Coreos medium
  theforeman.foreman.installation_medium:
    name: "Red Hat CoreOS"
    locations:
      - "{{ sat_loc }}"
    organizations:
      - "{{ sat_org }}"
    os_family: "Coreos"
    path: "http://localhost/pub/rhcos"
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    state: absent
