---

- name: Remove {{ sat_hostgroup }} hostgroup
  theforeman.foreman.hostgroup:
    name: "{{ sat_hostgroup }}"
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    state: absent

- name: Remove {{ sat_os }} OS
  theforeman.foreman.operatingsystem:
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    name: '{{ sat_os }}'
    major: "{{ sat_os_maj | int }}"
    state: absent

- name: Remove {{ sat_medium }} Medium
  theforeman.foreman.installation_medium:
    name: "{{ sat_medium }}"
    locations:
      - "{{ sat_loc }}"
    organizations:
      - "{{ sat_org }}"
    os_family: "Coreos"
    path: "http://localhost/pub/rhcos"
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    state: absent

- name: Remove Red Hat CoreOS PXELinux template
  theforeman.foreman.provisioning_template:
    server_url: "{{ sat_server }}"
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    validate_certs: "{{ sat_ssl_enabled }}"
    name: 'Red Hat CoreOS PXELinux'
    file_name: '{{ playbook_dir }}/rhcos_pxe_template.txt'
    state: absent
